networks:
  default: rinkeby
  mainnet-fork:
    explorer: https://api.etherscan.io/api
    cmd: ganache-cli
    cmd_settings:
      accounts: 10
      mnemonic: brownie
      fork: https://rinkeby.infura.io/v3/$WEB3_INFURA_PROJECT_ID
      default_balance: 250 ether
      chain_id: 4

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.1

autofetch_sources: true

compiler:
  solc:
    version: 0.8.4
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.1"
